# Generated by Django 4.1 on 2022-08-24 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=2)),
                ('player2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=2)),
                ('next_turn', models.CharField(max_length=25)),
                ('movements_played', models.IntegerField(default=0)),
                ('winner', models.CharField(default='', max_length=25, null=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), blank=True, size=3), default=[[None, None, None], [None, None, None], [None, None, None]], size=3)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
