# Generated by Django 4.1 on 2022-08-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=25)),
                ('player2', models.CharField(max_length=25)),
                ('next_turn', models.CharField(max_length=25)),
                ('movements_played', models.IntegerField(default=0)),
                ('winner', models.CharField(default='', max_length=25, null=True)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
