# Generated by Django 4.1 on 2022-08-17 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_game_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=['', '', '', '', '', '', '', ''], size=8),
        ),
    ]
