# Generated by Django 4.1 on 2022-08-17 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_game_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), blank=True, size=3), default=[[None, None, None], [None, None, None], [None, None, None]], size=3),
        ),
    ]
