# Generated by Django 4.1 on 2022-08-18 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_game_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default='X', size=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default='O', size=2),
        ),
    ]
