# Generated by Django 4.1 on 2022-08-18 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=2),
        ),
    ]
